name: flutter_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter

  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  riverpod: ^1.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
